services:
  # A PostgreSQL database
  - type: psql
    name: blog-database
    databaseName: blogdb
    plan: free # You can choose a paid plan for production
    ipAllowList: [] # Allows access from anywhere

  # The Node.js backend service
  - type: web
    name: blog-backend
    runtime: node
    plan: free # You can choose a paid plan for production
    branch: main # Or your default branch
    healthCheckPath: /
    envVars:
      - key: PGHOST
        fromService:
          type: psql
          name: blog-database
          property: host
      - key: PGDATABASE
        fromService:
          type: psql
          name: blog-database
          property: database
      - key: PGUSER
        fromService:
          type: psql
          name: blog-database
          property: user
      - key: PGPASSWORD
        fromService:
          type: psql
          name: blog-database
          property: password
      - key: JWT_SECRET # IMPORTANT: You must set this manually in the Render dashboard
        sync: false
    buildCommand: "npm install"
    startCommand: "node backend/server.js"
